-- ========= TABELA DE SERVIÇOS =========
-- Armazena os serviços oferecidos pelo salão.

CREATE TABLE public.servicos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  descricao text NULL,
  preco numeric(10, 2) NOT NULL,
  duracao_minutos integer NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Habilita a segurança em nível de linha (padrão no Supabase)
ALTER TABLE public.servicos ENABLE ROW LEVEL SECURITY;

-- Política de Acesso: Permite que QUALQUER pessoa leia os serviços.
-- Isso é necessário para que seu site possa listar os serviços disponíveis.
CREATE POLICY "Permitir leitura pública dos serviços"
ON public.servicos
FOR SELECT
USING (true);


-- ========= TABELA DE AGENDAMENTOS =========
-- Armazena os agendamentos feitos pelos clientes.

-- Primeiro, criamos um "tipo" personalizado para o status, o que ajuda a evitar erros.
CREATE TYPE public.status_agendamento AS ENUM ('confirmado', 'cancelado', 'concluido');

CREATE TABLE public.agendamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_servico bigint NOT NULL REFERENCES public.servicos(id),
  horario_inicio timestamp with time zone NOT NULL,
  horario_fim timestamp with time zone NOT NULL,
  nome_cliente text NOT NULL,
  telefone_cliente varchar(20) NOT NULL,
  status public.status_agendamento DEFAULT 'confirmado' NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Habilita a segurança em nível de linha
ALTER TABLE public.agendamentos ENABLE ROW LEVEL SECURITY;

-- Política de Acesso: Permite que QUALQUER pessoa veja os horários já agendados.
-- Isso é crucial para que o calendário no seu site saiba quais horários estão ocupados.
CREATE POLICY "Permitir leitura pública dos agendamentos"
ON public.agendamentos
FOR SELECT
USING (true);

-- Política de Acesso: Permite que QUALQUER pessoa crie um novo agendamento.
-- Essencial para o formulário de agendamento funcionar.
CREATE POLICY "Permitir inserção pública de agendamentos"
ON public.agendamentos
FOR INSERT
WITH CHECK (true);


-- ========= DADOS DE EXEMPLO (OPCIONAL) =========
-- Insira alguns serviços para testar. Descomente as linhas abaixo se quiser.

-- INSERT INTO public.servicos (nome, descricao, preco, duracao_minutos)
-- VALUES
--   ('Corte de Cabelo Feminino', 'Corte, lavagem e secagem.', 70.00, 60),
--   ('Manicure Simples', 'Cutilagem e esmaltação das unhas das mãos.', 25.00, 45),
--   ('Pedicure Simples', 'Cutilagem e esmaltação das unhas dos pés.', 30.00, 45),
--   ('Design de Sobrancelha', 'Modelagem de sobrancelha com pinça.', 35.00, 30);