-- ========= TABELA DE PROFISSIONAIS =========
-- Armazena os profissionais do salão.

CREATE TABLE public.profissionais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Habilita segurança e cria política de leitura pública
ALTER TABLE public.profissionais ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura pública dos profissionais"
ON public.profissionais FOR SELECT USING (true);


-- ========= TABELA DE HORÁRIOS DISPONÍVEIS =========
-- O coração da nova funcionalidade. Armazena cada slot de tempo disponível.

-- Cria um tipo para o status do horário
CREATE TYPE public.status_horario AS ENUM ('disponivel', 'reservado');

CREATE TABLE public.horarios_disponiveis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profissional bigint NOT NULL REFERENCES public.profissionais(id),
  horario_inicio timestamp with time zone NOT NULL,
  status public.status_horario DEFAULT 'disponivel' NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  -- Garante que não se pode cadastrar o mesmo horário para o mesmo profissional duas vezes
  UNIQUE (id_profissional, horario_inicio)
);

-- Habilita segurança e cria políticas de acesso
ALTER TABLE public.horarios_disponiveis ENABLE ROW LEVEL SECURITY;

-- Qualquer pessoa pode ver os horários disponíveis
CREATE POLICY "Permitir leitura pública dos horários"
ON public.horarios_disponiveis FOR SELECT USING (true);

-- Por enquanto, qualquer pessoa pode criar e deletar horários.
-- No futuro, isso seria restrito a administradores.
CREATE POLICY "Permitir criação de horários"
ON public.horarios_disponiveis FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir remoção de horários"
ON public.horarios_disponiveis FOR DELETE USING (true);

CREATE POLICY "Permitir atualização de horários"
ON public.horarios_disponiveis FOR UPDATE USING (true);


-- ========= DADOS DE EXEMPLO (OPCIONAL, MAS RECOMENDADO) =========
INSERT INTO public.profissionais (nome) VALUES ('Ana Silva'), ('Carlos Souza');
